- name: Load Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven

- name: Install MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.maidevops.fun -u{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/shipping:DB_USER url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }} -p{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/shipping:DB_PASS url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }} < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data