#- name: Load Python
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: python
- name: Load common main
  ansible.builtin.import_role:
    name: common

- name: Load Docker
  ansible.builtin.import_role:
    name: common
    tasks_from: docker

- name: Launch Docker Container
  community.docker.docker_container:
    name: payment
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment
    ports:
      - "8080:8080"
    env:
      CART_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/payment:CART_HOST url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }}"
      CART_PORT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/payment:CART_PORT url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }}"
      USER_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/payment:USER_HOST url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }}"
      USER_PORT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/payment:USER_PORT url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }}"
      AMQP_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/payment:AMQP_HOST url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }}"
      AMQP_USER: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/payment:AMQP_USER url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }}"
      AMQP_PASS: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/payment:AMQP_PASS url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }}"
