- name: Copy RabbitMQ Repo File
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install RabbitMQ Server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Server
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add RabbitMQ User
  ansible.builtin.shell: rabbitmqctl add_user {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/rabbitmq:APP_USER url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }} {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/rabbitmq:APP_PASSWORD url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }} ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
