- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Set Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/mysql:ROOT_PASSWORD url=http://vault-internal.maidevops.fun:8200 auth_method=token token=' + token) }}

