- name: Download Hashicorp Repo File
  ansible.builtin.copy:
    src: hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: Copy Vault Config
  ansible.builtin.copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: Start Service
  ansible.builtin.systemd_service:
    name: vault
    state: restarted
    enabled: yes