- name: Copy Hashicorp Repo File
  ansible.builtin.copy:
    src: hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Vault
  ansible.builtin.dnf:
    name: vault
    state: installed
# vault installation